### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by tamb** [morgosus/fitboy-sense#3]
Can  the left side font be slightly bigger, at least for the time?

The bar that says "Good Afternoon" could also fit the current temperature on the right side.

**Comment by morgosus** [comment]
While it may seem so, these wouldn't actually be UI improvements.

Now, while the "good afternoon" could fit the current temperature, from the perspective of UI/UX, the right side would cause the stat to vary in position throughout the week, and the left side... Well, -54°C Good Evening doesn't sound too great.

The main issues, however, would come from increased **power consumption** (which isn't worth it, since you can get weather by swiping up by default), and the text/temperature being covered by notifications, such as night mode or Bluetooth error, leading to **cluttered** feeling.

Technically it could, but all the dimensions, including the font size and placement have been calculated to be pretty much optimal. Any smaller, and it becomes hard to read for everyone. Any larger, and the dimensions are thrown off.

Essentially, to implement these, and maintain the same level of quality (4.8/5 stars with thousands of ratings), the entire interface would have to be redesigned. And even then it would be kind of a gamble, which I wouldn't push on the thousands of users.

Alternatively, this could be implemented via settings, but even then it's taking up space and resources - and since Fitbit Sense is essentially a miniature 90s computer and its apps suffer when not optimized, it'd be too much loss for too little gain.
